config/routes.rb
Rails.application.routes.draw do
  get 'mypage/show'
  devise_for :users,
  controllers: { sessions: 'users/sessions', 
                 omniauth_callbacks: 'users/omniauth_callbacks', 
                 registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :tops ,only:[:index]
  resources :products do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    collection do
      get 'transaction'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search_brand', defaults: { format: 'json' }
      get 'get_image', defaults: { format: 'json' }
      get 'delete_image', defaults: { format: 'json' }
    end
  end

  resources :categories do
  end

  

  resources :brands do
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, product_id: params[:product_id])
    @likes = Like.where(product_id: params[:product_id])
    # @products = Product.all
    @product = Product.find(params[:product_id])
    # redirect_to product_path(@product)
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, product_id: params[:product_id])
    like.destroy
    @likes = Like.where(product_id: params[:product_id])
    # @products = Product.all
    @product = Product.find(params[:product_id])
    # redirect_to product_path(@product)
  end
end

app/views/likes/_like.html.haml
- if product.like_user(current_user.id)
  = button_to product_like_path(like, product_id: product.id), method: :delete, class: "products__right__box__product__form__buys__like", id: "like-button", remote: true do
    %span
      お気に入りに追加
    = image_tag "icon_red_heart.png", size: "18"
    = product.likes_count
- else
  = button_to product_likes_path(product), method: :post, class: "products__right__box__product__form__buys__like", id: "like-button", remote: true do
    %span
      お気に入りに追加
    = image_tag "icon_heart.png", size: "18"
    = product.likes_count

app/views/likes/create.js.erb
$("#likes_buttons_<%=@product.id%>").html("<%= escape_javascript(render partial: 'like', locals: { product: @product, like: @like, likes: @likes}) %>");

app/views/likes/destroy.js.erb
$("#likes_buttons_<%=@product.id%>").html("<%= escape_javascript(render partial: 'like', locals: { product: @product, likes: @likes })%>");