config/routes.rb
Rails.application.routes.draw do
  get 'mypage/show'
  devise_for :users,
  controllers: { sessions: 'users/sessions', 
                 omniauth_callbacks: 'users/omniauth_callbacks', 
                 registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :tops ,only:[:index]
  resources :products do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    collection do
      get 'transaction'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search_brand', defaults: { format: 'json' }
      get 'get_image', defaults: { format: 'json' }
      get 'delete_image', defaults: { format: 'json' }
    end
  end

  resources :categories do
  end

  

  resources :brands do
  end

end

app/views/shared/_delete-modal.html.haml
.flex1
  .modalcontainer
    .flex2
      .modal
        .close
          %span 
            +
        .content
          %h2 
            削除確認
          %p 
            削除すると二度と復活できません。
            %br
            同じ商品を出品する必要があります。
            %br
            %br
            %br/
            本当に削除しますか？
        .buttons
          =link_to "キャンセル", "#0"
          =link_to "削除", product_path(@product), method: :delete
 
  

app/views/shared/_error.html.haml
- if flash[:error].present? && flash[:error][key].present?
  - flash[:error][key].each do |message|
    %p.error-message
      = message

app/views/shared/_exhibit.html.haml
.main-top__exhibit
  = link_to new_product_path, class: "main-top__exhibit__link" do
    .main-top__exhibit__link__circle
      .main-top__exhibit__link__circle__title 出品
      = fa_icon "camera", class: "camera__icon"

app/views/shared/_footer.html.haml
.top__footer
  .top__footer__box
    .top__footer__box__top
      = link_to 'お問い合わせ', class: "link"
      = link_to 'ヘルプ', class: "link"
    .top__footer__box__bottom
      .top__footer__box__bottom__left
        .top__footer__box__bottom__left__nav
          %span 日本
        .top__footer__box__bottom__left__at © 2019 Cross Culture, Inc. All Rights Reserved

app/views/shared/_header.html.haml
.top__header
  .top__header__box
    .top__header__box__top
      .top__header__box__top__box
        %ul.top__header__box__top__box__brand
          = render 'brands/window'
        .top__header__box__top__box__mypage
          =link_to "https://www.google.com/", class: "top__header__box__top__box__mypage__link" do
            = fa_icon "user-circle", class: "top__header__box__top__box__mypage__icon"
        .top__header__box__top__box__logout
          =link_to destroy_user_session_path, class: "top__header__box__top__box__logout__link", method: :delete do
            = fa_icon "outdent", class: "top__header__box__top__box__logout__link__icon"
    .top__header__box__under
      .top__header__box__under__icon
        = image_tag ("CC-icon.jpg"), height: '60', width: '100'
      = render 'categories/window'
      = form_tag('/search', method: :get, class: 'search-form') do
        %button.btn-search{title: "検索", type: "submit"}
          = fa_icon "search", class: "search-form__icon"
        %input.search-form__input{name: "keyword", placeholder: "SEACH", type: "text", value: ""}    