config/routes.rb
Rails.application.routes.draw do
  get 'mypage/show'
  devise_for :users,
  controllers: { sessions: 'users/sessions', 
                 omniauth_callbacks: 'users/omniauth_callbacks', 
                 registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :tops ,only:[:index]
  resources :products do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    collection do
      get 'transaction'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search_brand', defaults: { format: 'json' }
      get 'get_image', defaults: { format: 'json' }
      get 'delete_image', defaults: { format: 'json' }
    end
  end

  resources :categories do
  end

  

  resources :brands do
  end

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  has_ancestry
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def show
    @brand = Brand.find(params[:id])
  end
end

app/views/brands/_window.html.haml
- @persons.each do |person|
  = link_to brand_path(person), class: "top__header__box__top__box__brand__list__one" , id: "#{person.id}"do
    = image_tag ("#{person.image_was}"), height: '30', width: '40'

app/views/brands/show.html.haml
.category-wrapper
  = render 'shared/header'
  .category
    .category__box
      .category__box__container
        %h2.category__box__container__title
          メンズ商品一覧
      .category__box__container__products
        .category__box__container__products__product 
          =link_to "#0", class: "link" do
            =image_tag "nike_shose.webp"
        .category__box__container__products__product 
          =link_to "#0", class: "link" do
            =image_tag "nike_shose.webp"
        .category__box__container__products__product 
          =link_to "#0", class: "link" do
            =image_tag "nike_shose.webp"
        .category__box__container__products__product 
          =link_to "#0", class: "link" do
            =image_tag "nike_shose.webp"
        .category__box__container__products__product 
          =link_to "#0", class: "link" do
            =image_tag "nike_shose.webp"
  = render 'shared/footer'